name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check code
      uses: actions/checkout@v4
    
      with:
       fetch-depth: 0
    - name : Docker login
      run: |
        echo "Iniciando Login To Docker Hub" 
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
        echo "Login To Docker Hub Success"
    - name: Build the Docker image
      run: docker build -t pierrechavez/docker-graphql:0.0.1 .
    - name: Push the Docker image
      run: docker push pierrechavez/docker-graphql:0.0.1