name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check code
      uses: actions/checkout@v4
    
      with:
       fetch-depth: 0
       
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version
    - name : Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "Iniciando Login To Docker Hub" 
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
        echo "Login To Docker Hub Success"
    - name: Build the Docker image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker build -t pierrechavez/docker-graphql:$NEW_VERSION .
        docker build -t pierrechavez/docker-graphql:latest .
    - name: Push the Docker image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker push pierrechavez/docker-graphql:$NEW_VERSION
        docker push pierrechavez/docker-graphql:latest